'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace WebServiceBanxico

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code"),
     System.Web.Services.WebServiceBindingAttribute(Name:="DgieWSPortSoapBinding", [Namespace]:="http://ws.dgie.banxico.org.mx")>
    Partial Public Class DgieWS
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

        Private reservasInternacionalesBanxicoOperationCompleted As System.Threading.SendOrPostCallback

        Private tasasDeInteresBanxicoOperationCompleted As System.Threading.SendOrPostCallback

        Private tiposDeCambioBanxicoOperationCompleted As System.Threading.SendOrPostCallback

        Private udisBanxicoOperationCompleted As System.Threading.SendOrPostCallback

        Private useDefaultCredentialsSetExplicitly As Boolean

        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Maiz.My.MySettings.Default.Maiz_WebServiceBanxico_DgieWS
            If (Me.IsLocalFileSystemWebService(Me.Url) = True) Then
                Me.UseDefaultCredentials = True
                Me.useDefaultCredentialsSetExplicitly = False
            Else
                Me.useDefaultCredentialsSetExplicitly = True
            End If
        End Sub

        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = True) _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = False)) _
                            AndAlso (Me.IsLocalFileSystemWebService(Value) = False)) Then
                    MyBase.UseDefaultCredentials = False
                End If
                MyBase.Url = Value
            End Set
        End Property

        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = Value
                Me.useDefaultCredentialsSetExplicitly = True
            End Set
        End Property

        '''<remarks/>
        Public Event reservasInternacionalesBanxicoCompleted As reservasInternacionalesBanxicoCompletedEventHandler

        '''<remarks/>
        Public Event tasasDeInteresBanxicoCompleted As tasasDeInteresBanxicoCompletedEventHandler

        '''<remarks/>
        Public Event tiposDeCambioBanxicoCompleted As tiposDeCambioBanxicoCompletedEventHandler

        '''<remarks/>
        Public Event udisBanxicoCompleted As udisBanxicoCompletedEventHandler

        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://ws.dgie.banxico.org.mx", ResponseNamespace:="http://ws.dgie.banxico.org.mx")>
        Public Function reservasInternacionalesBanxico() As <System.Xml.Serialization.SoapElementAttribute("result")> String
            Dim results() As Object = Me.Invoke("reservasInternacionalesBanxico", New Object(-1) {})
            Return CType(results(0), String)
        End Function

        '''<remarks/>
        Public Overloads Sub reservasInternacionalesBanxicoAsync()
            Me.reservasInternacionalesBanxicoAsync(Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub reservasInternacionalesBanxicoAsync(ByVal userState As Object)
            If (Me.reservasInternacionalesBanxicoOperationCompleted Is Nothing) Then
                Me.reservasInternacionalesBanxicoOperationCompleted = AddressOf Me.OnreservasInternacionalesBanxicoOperationCompleted
            End If
            Me.InvokeAsync("reservasInternacionalesBanxico", New Object(-1) {}, Me.reservasInternacionalesBanxicoOperationCompleted, userState)
        End Sub

        Private Sub OnreservasInternacionalesBanxicoOperationCompleted(ByVal arg As Object)
            If (Not (Me.reservasInternacionalesBanxicoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent reservasInternacionalesBanxicoCompleted(Me, New reservasInternacionalesBanxicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://ws.dgie.banxico.org.mx", ResponseNamespace:="http://ws.dgie.banxico.org.mx")>
        Public Function tasasDeInteresBanxico() As <System.Xml.Serialization.SoapElementAttribute("result")> String
            Dim results() As Object = Me.Invoke("tasasDeInteresBanxico", New Object(-1) {})
            Return CType(results(0), String)
        End Function

        '''<remarks/>
        Public Overloads Sub tasasDeInteresBanxicoAsync()
            Me.tasasDeInteresBanxicoAsync(Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub tasasDeInteresBanxicoAsync(ByVal userState As Object)
            If (Me.tasasDeInteresBanxicoOperationCompleted Is Nothing) Then
                Me.tasasDeInteresBanxicoOperationCompleted = AddressOf Me.OntasasDeInteresBanxicoOperationCompleted
            End If
            Me.InvokeAsync("tasasDeInteresBanxico", New Object(-1) {}, Me.tasasDeInteresBanxicoOperationCompleted, userState)
        End Sub

        Private Sub OntasasDeInteresBanxicoOperationCompleted(ByVal arg As Object)
            If (Not (Me.tasasDeInteresBanxicoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent tasasDeInteresBanxicoCompleted(Me, New tasasDeInteresBanxicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://ws.dgie.banxico.org.mx", ResponseNamespace:="http://ws.dgie.banxico.org.mx")>
        Public Function tiposDeCambioBanxico() As <System.Xml.Serialization.SoapElementAttribute("result")> String
            Dim results() As Object = Me.Invoke("tiposDeCambioBanxico", New Object(-1) {})
            Return CType(results(0), String)
        End Function

        '''<remarks/>
        Public Overloads Sub tiposDeCambioBanxicoAsync()
            Me.tiposDeCambioBanxicoAsync(Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub tiposDeCambioBanxicoAsync(ByVal userState As Object)
            If (Me.tiposDeCambioBanxicoOperationCompleted Is Nothing) Then
                Me.tiposDeCambioBanxicoOperationCompleted = AddressOf Me.OntiposDeCambioBanxicoOperationCompleted
            End If
            Me.InvokeAsync("tiposDeCambioBanxico", New Object(-1) {}, Me.tiposDeCambioBanxicoOperationCompleted, userState)
        End Sub

        Private Sub OntiposDeCambioBanxicoOperationCompleted(ByVal arg As Object)
            If (Not (Me.tiposDeCambioBanxicoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent tiposDeCambioBanxicoCompleted(Me, New tiposDeCambioBanxicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://ws.dgie.banxico.org.mx", ResponseNamespace:="http://ws.dgie.banxico.org.mx")>
        Public Function udisBanxico() As <System.Xml.Serialization.SoapElementAttribute("result")> String
            Dim results() As Object = Me.Invoke("udisBanxico", New Object(-1) {})
            Return CType(results(0), String)
        End Function

        '''<remarks/>
        Public Overloads Sub udisBanxicoAsync()
            Me.udisBanxicoAsync(Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub udisBanxicoAsync(ByVal userState As Object)
            If (Me.udisBanxicoOperationCompleted Is Nothing) Then
                Me.udisBanxicoOperationCompleted = AddressOf Me.OnudisBanxicoOperationCompleted
            End If
            Me.InvokeAsync("udisBanxico", New Object(-1) {}, Me.udisBanxicoOperationCompleted, userState)
        End Sub

        Private Sub OnudisBanxicoOperationCompleted(ByVal arg As Object)
            If (Not (Me.udisBanxicoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent udisBanxicoCompleted(Me, New udisBanxicoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub

        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing) _
                        OrElse (url Is String.Empty)) Then
                Return False
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024) _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return True
            End If
            Return False
        End Function
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")>
    Public Delegate Sub reservasInternacionalesBanxicoCompletedEventHandler(ByVal sender As Object, ByVal e As reservasInternacionalesBanxicoCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code")>
    Partial Public Class reservasInternacionalesBanxicoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), String)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")>
    Public Delegate Sub tasasDeInteresBanxicoCompletedEventHandler(ByVal sender As Object, ByVal e As tasasDeInteresBanxicoCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code")>
    Partial Public Class tasasDeInteresBanxicoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), String)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")>
    Public Delegate Sub tiposDeCambioBanxicoCompletedEventHandler(ByVal sender As Object, ByVal e As tiposDeCambioBanxicoCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code")>
    Partial Public Class tiposDeCambioBanxicoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), String)
            End Get
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")>
    Public Delegate Sub udisBanxicoCompletedEventHandler(ByVal sender As Object, ByVal e As udisBanxicoCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0"),
     System.Diagnostics.DebuggerStepThroughAttribute(),
     System.ComponentModel.DesignerCategoryAttribute("code")>
    Partial Public Class udisBanxicoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
